export default {
  // SCREENS

  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  PROFILE_SETUP_SCREEN:'PROFILE_SETUP_SCREEN',

  //STACK
  SIGN_UP_STACK: 'SIGN_UP_STACK',
  MAIN_STACK: 'MAIN_STACK',
  USER_SETUP_STACK:'USER_SETUP_STACK'
} as const;
